proxy:
  tracing:
    enabled: true
    collector:
      endpoint: otel-collector-opentelemetry-collector.opentelemetry:4317
      meshIdentity:
        serviceAccountName: otel-collector-opentelemetry-collector
        namespace: opentelemetry
